### ISSUE TITLE
Container crashando quando a url não está no ar

### ISSUE THREAD

**Issue by antiogenes** [osgurisdosre/mongoshake-prometheus-exporter#5]
Conforme documentação do mongoshake, a API de status tem mais de um endpoint para monitoramento, em resumo na porta 9101 pode ser obtido dados da replicação full e na porta 9100 dados da replicação incremental:

    # http api interface. Users can use this api to monitor mongoshake.
    # `curl 127.0.0.1:9100`.
    full_sync.http_port = 9101
    incr_sync.http_port = 9100
    system_profile_port = 9200
    
    Alimentei a URL_LIST com os endpoints nas portas 9100 e 9101, conforme exemplo abaixo:
    
            - name: URL_LIST
          value: http://localhost:9100/repl,http://localhost:9101/progress,http://localhost:9101/sentinel
          
O problema é que quando o full está rodando, a porta do incremental não fica disponível, e vice e versa, e quando a aplicação tenta checar alguma url que a porta não está disponível, o container ficar crashando.

**Comment by emdneto** [comment]
https://github.com/osgurisdosre/mongoshake-prometheus-exporter/commit/2342161106bd7fa986b4175b50cc2462dd836440
